apiVersion: apps/v1
kind: Deployment
metadata:
  name: skolvalarskurs7-deployment
  labels:
    app: skolvalarskurs7
spec:
  replicas: 3  # Number of desired pods
  selector:
    matchLabels:
      app: skolvalarskurs7
  template:
    metadata:
      labels:
        app: skolvalarskurs7
    spec:
      containers:
      - name: skolvalarskurs7-container
        image: gcr.io/your-project-id/skolvalarskurs7:latest  # Replace with your image URL
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
